#!/usr/bin/env bash
die() {
  echo $1
  exit 1
}
install() {
  group=$1
  artifact=$2
  version=$3
  file=$4
  [ -f "${file}" ] || die "Can't find ${file}"
  mvn install:install-file -DgroupId=${group} -DartifactId=${artifact} -Dversion=${version} -Dpackaging=jar -Dfile=${file} || die "Failed to install #{artifact}"
  cat <<EOF
  <dependency>
    <groupId>${group}</groupId>
    <artifactId>${artifact}</artifactId>
    <version>${version}</version>
  </dependency>
EOF
}

install org.masukomi aspirin 0.8.3 lib/aspirin-0.8.3.jar
install org.safehaus.jug jug 2.0.0 lib/jug-lgpl-2.0.0.jar
install org.sfee inmemorysfee 1.0.1 lib/inmemorysfee-1.0.1.jar
